name: github-action
run-name: ${{ github.actor }} is out building GitHub Actions

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - '**' 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Maven Projects
        run: |
          mvn clean package -f ./food-ordering/pom.xml
          mvn clean package -f ./food-delivery/pom.xml
          mvn clean package -f ./restaurant-management/pom.xml

      - name: Docker Build and push for FoodOrdering
        uses: docker/build-push-action@v4
        with:
          context: ./food-ordering
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/food-ordering:latest
            ghcr.io/${{ github.repository }}/food-ordering:${{ github.ref_name }}
            
      - name: Docker Build and push for FoodDelivery
        uses: docker/build-push-action@v4
        with:
          context: ./food-delivery
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/food-delivery:latest
            ghcr.io/${{ github.repository }}/food-delivery:${{ github.ref_name }}
            
      - name: Docker Build and push for RestaurantManagement
        uses: docker/build-push-action@v4
        with:
          context: ./restaurant-management
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/restaurant-management:latest
            ghcr.io/${{ github.repository }}/restaurant-management:${{ github.ref_name }}
            
