---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-ordering
  labels:
    app: food-ordering
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-ordering
  template:
    metadata:
      labels:
        app: food-ordering
    spec:
      containers:
        - name: food-ordering
          image: username/food-ordering:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: food-delivery
  labels:
    app: food-delivery
spec:
  replicas: 1
  selector:
    matchLabels:
      app: food-delivery
  template:
    metadata:
      labels:
        app: food-delivery
    spec:
      containers:
        - name: food-delivery
          image: username/food-delivery:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-management
  labels:
    app: restaurant-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-management
  template:
    metadata:
      labels:
        app: restaurant-management
    spec:
      containers:
        - name: restaurant-management
          image: username/restaurant-management:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5


---


apiVersion: v1
kind: Service
metadata:
  name: food-ordering
  labels:
    app: food-ordering
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: food-ordering


---


apiVersion: v1
kind: Service
metadata:
  name: food-delivery
  labels:
    app: food-delivery
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: food-delivery


---


apiVersion: v1
kind: Service
metadata:
  name: restaurant-management
  labels:
    app: restaurant-management
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: restaurant-management

